prefix foaf:	<http://xmlns.com/foaf/0.1/>
prefix cob:	<http://cobusiness.fr/ontologies/barter.owl.n3#>
prefix oxi:	<http://omerxi.com/ontologies/core.owl.ttl#>
prefix oxid:  <http://omerxi.com/resource/>
prefix dc:	<http://purl.org/dc/elements/1.1/>
prefix vcard:	<http://www.w3.org/2006/vcard/ns#>
prefix fn:	<http://www.w3.org/2005/xpath-functions#>
prefix afn:	<http://jena.hpl.hp.com/ARQ/function#>

# {"url": "http://www.my-phone-supplier.com", "who": "John Doo", "where": "75013 Paris", "timeout": 20000}

CONSTRUCT {
  _:query oxi:url <SERVER> ;
	oxi:remote "http://192.168.1.13:4444/wd/hub" ;
          oxi:who ?FIRST_LAST_NAME ;
          oxi:who ?NAME_MANAGER ;
          oxi:where ?CODE_LOC ;
          oxi:timeout 60000 .
} WHERE {
   # GRAPH ?G {
     ?X oxi:id <ID> ;
        vcard:postal-code ?PC ;
        vcard:locality ?LOC .
     OPTIONAL {
	?X foaf:lastName ?LASTNAME ; foaf:firstName ?FIRSTNAME . }
     OPTIONAL { ?X foaf:name ?NAME }
     OPTIONAL { ?X oxi:manager ?MANAGER }
     BIND ( fn:concat( ?FIRSTNAME , " ", ?LASTNAME ) AS ?FIRST_LAST_NAME )
     BIND ( fn:concat( ?PC , " ", ?LOC ) AS ?CODE_LOC )
     BIND ( fn:concat( ?NAME , " ", ?MANAGER ) AS ?NAME_MANAGER )
   # }
}
